In [ ]:
#Agenda
#Function of Numpy Arrays - arange()
#Function of Numpy Arrays - sqrt()
#Function of Numpy Arrays - exp()
#Function of Numpy Arrays - random()
#Function of Numpy Arrays - add()
#Function of Numpy Arrays - maximum()
#Numpy Additional documentation - numpy.org, doccs.scipy.org

In [1]:
import numpy as np

In [2]:
#Function of Numpy Arrays - arange()

A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
#example2

B = np.arange(5,10)
print(B)

[5 6 7 8 9]


In [4]:
#example3

C = np.arange(5,10,2)
print(C)

[5 7 9]


In [5]:
#Function of Numpy Arrays - sqrt()

D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [8]:
#Function of Numpy Arrays - exp()

E = np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [11]:
#Function of Numpy Arrays - random()

F = np.random.randn(5)
print(F)

#example2
F = np.random.randn(5,5)
print(F)

[-0.99131234  0.40003322  0.22278396  0.98689989  0.50678309]
[[ 0.42352679  0.8235933   0.53585377  2.33963343 -0.25139778]
 [ 0.979146    0.01656461  1.58491296 -0.66528506 -0.20890075]
 [-0.50743727  0.64114348  0.14411753  0.22153724 -1.43018351]
 [-0.17841853  0.48196809  0.42316675 -0.19329965  0.82445221]
 [-0.9446725   1.81617103  0.23579358 -0.16570605  1.18759159]]


In [12]:
#Function of Numpy Arrays - add()

print(A)
print(D)

G = np.add(A,D)
print(G)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]
[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [16]:
#Function of Numpy Arrays - maximum()

H = np.array([1,5,7,10])
I = np.array([2,4,6,8])
print(H)
print(I)

J = np.maximum(H,I)
print(J)

[ 1  5  7 10]
[2 4 6 8]
[ 2  5  7 10]
