In [ ]:
#Agenda
#Why do we need to save arrays to hard drive?
#Saving single array
#Loading single array
#Saving multiple array
#Loading multiple array
#Saving array to text file
#Loading array from text file
#What is delimiter?

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Why do we need to save arrays to hard drive?
#Due to memory block, if ram if unable to process, it deletes the stored array so we have to run a large chunk of code again which we don't want so we save it into a file or hard drive and import it whenever we need them.

In [4]:
#Saving single array

np.save('Saved Array', arr)

In [5]:
#Loading single array

load_Array1 = np.load('Saved Array.npy')
print(load_Array1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Saving multiple array

arr2 = np.arange(25)
arr3 = np.arange(5)

np.savez('saved_archive.npz', x=arr2, y=arr3)

In [8]:
#Loading multiple array

load_npz = np.load('saved_archive.npz')
print(load_npz['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [9]:
#Saving array to text file

np.savetxt('myarray.txt', arr2, delimiter=',')

In [10]:
#Loading array from text file

load_file = np.loadtxt('myarray.txt', delimiter=',')
print(load_file)

#you can see that saved intger value are loaded as floating values i.e. with decimal points

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [ ]:
#What is delimiter?

#used as a seprator for array elements in txt file