In [ ]:
#Agenda
#Introduction to Indexes
#Access individual Array Elements
#Slicing of Array Indexes arr[start:stop:step]
#Updating array using slices
#Interesting point about slicing - Memory allocation - view vs copy
#Advantages
#copy() function => Creating new numpy memory for array

In [1]:
import numpy as np

In [2]:
arr = np.arange(100,160,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [3]:
#Introduction to Indexes
#used to access array elements
#example:
print(arr[2])

104


In [5]:
#Access individual Array Elements
for i in range(30):
    print(arr[i]," ")

100  
102  
104  
106  
108  
110  
112  
114  
116  
118  
120  
122  
124  
126  
128  
130  
132  
134  
136  
138  
140  
142  
144  
146  
148  
150  
152  
154  
156  
158  


In [6]:
#Slicing of Array Indexes arr[start:stop:step]

print(arr[0:5:1])

[100 102 104 106 108]


In [7]:
#updating array using slices

arr[0:5] = 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [20]:
#Interesting point about slicing - Memory allocation - view vs copy

arr2 = arr[10:15]
print(arr2)

#here whatever changes are donein arr2 will be reflected to arr, to overcome this we use copy() function

arr2[:] = 1
print(arr2)

[1 1 1 1 1]
[1 1 1 1 1]


In [21]:
#copy() function => Creating new numpy memory for array

arr3 = arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1   1   1   1   1   1 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [22]:
arr3[:] = 0
print(arr)
print(arr3)

#you will see that changes in arr3 are not reflected back to arr

[  0   0   0   0   1   1   1   1   1   1   1   1   1   1   1 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
