In [ ]:
#Agenda
#Introduction to Numpy
#Creating Numpy 1d Array
#Creating 2d Np Array
#Finding dimensions of Array - shape
#Finding datatype of Array - dtype
#Array creation and initialisation functions - zeros
#Array creation and initialisation functions - ones
#Array creation and initialisation functions - empty
#Array creation and initialisation functions - eye
#Array creation and initialisation functions - arange
#Summarize

In [4]:
import numpy as np

In [5]:
#Creating Numpy 1d Array
mylist1 = [101,102,103]

myArray = np.array(mylist1)
print(myArray)

[101 102 103]


In [6]:
#Creating 2d Np Array
mylist2 = [201,202,203]

myArray2D = np.array([mylist1,mylist2])
print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [7]:
#Finding dimensions of Array - shape

print("myArray Dimensions - ")
print(myArray.shape)
print("myArray2D Dimensions - ")
print(myArray2D.shape)

myArray Dimensions - 
(3,)
myArray2D Dimensions - 
(2, 3)


In [8]:
#Finding datatype of Array - dtype

print("myArray Datatype - ")
print(myArray.dtype)
print("myArray2D Datatype - ")
print(myArray2D.dtype)

myArray Datatype - 
int32
myArray2D Datatype - 
int32


In [9]:
#Array creation and initialisation functions - zeros

zero_array = np.zeros(5)
print(zero_array)

zero_array2D = np.zeros([5, 5])
print(zero_array2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#Array creation and initialisation functions - ones

print("1D:")
ones_array = np.ones(5)
print(ones_array)
print("2D:")
ones_array2D = np.ones([5,5])
print(ones_array2D)

1D:
[1. 1. 1. 1. 1.]
2D:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#Array creation and initialisation functions - empty

print("1D:")
empty_array = np.empty(5)
print(empty_array)
print("2D:")
empty_array2D = np.empty([5,5])
print(empty_array2D)

#all values are one because 1 is there in cache

1D:
[1. 1. 1. 1. 1.]
2D:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
#Array creation and initialisation functions - eye
#it is used to create identity matrix - can only create 2D matices

identity_array = np.eye(3)
print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#Array creation and initialisation functions - arange
#it creates array with Arithematic progression for upto given n values

AP_array = np.arange(0,50,2)
print(AP_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
